---

### common.yml:main.yml

# #SELinuxを"disabled"にして無効に。
# - name: Configure / SELinux Disabled
#   selinux:
#     policy: targeted
#     state: disabled

# #タイムゾーンを変更する
# - name: Set Timezone
#   timezone:
#     name: "{{ common.timezone }}"

# #localeの設定を変更する。
# #もし、すでの設定先のLANGだった場合スキップする。
# - name: Change locale Setting
#   command: localectl set-locale LANG={{ common.lang }}
#   when: ansible_env.LANG != common.lang
#   register: locale_facts

- name: comment out PermitRootLogin yes
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^PermitRootLogin yes"
    regexp: "^#PermitRootLogin yes"
    line: "#PermitRootLogin yes"

- name: add PermitRootLogin no
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^PermitRootLogin no"
    insertafter: '^#PermitRootLogin yes'
    line: "PermitRootLogin no"

- name: reboot sshd.service
  service:
    name: sshd
    state: restarted

- name: Allow ssh through firewall
  ufw:
    proto: tcp
    src: 192.168.10.0/24
    port: 22
    rule: allow

- name: Set ufw policy
  ufw:
    state: enabled
    direction: incoming
    policy: deny

- name: apt update
  apt:
    update_cache: yes
- name: apt upgrade
  apt:
    upgrade: yes
