---

### common.yml:main.yml

- name: 
  service:
    name: ufw
    state: started
    enabled: yes

- name: Allow minecraft through firewall
  ufw:
    name: Minecraft
    src: 192.168.10.0/24
    rule: allow

- name: make script which generate iptables cmd
  copy:
    src: ./etc/ufw/allow_jp_iplist.sh
    dest: /etc/ufw/allow_jp_iplist.sh
    owner: root
    group: root
    mode: 0755

- name: make minecraft's application file 
  copy:
    src: ./etc/ufw/applications.d/minecraft-server
    dest: /etc/ufw/applications.d/minecraft-server
    owner: root
    group: root
    mode: 0755

#- name: execute
#  shell: /etc/ufw/allow_jp_iplist.sh
