---

### common.yml:main.yml

- name: apt install pip
  apt:
    name: python3-pip

- name: pip install boto3
  pip:
    name: boto3

- name: pip install awscli
  pip:
    name: awscli

- name: add user.
  user: 
    name: '{{ ddns.user_name }}'

- name: make minecraft directory
  file:
    path: /opt/ddns
    state: directory
    owner: '{{ ddns.user_name }}'
    group: '{{ ddns.user_name }}'
    mode: 0755
    recurse: true

- name: make script which generate iptables cmd
  copy:
    src: ./opt/ddns/ddns.py
    dest: /opt/ddns/ddns.py
    owner: '{{ ddns.user_name }}'
    group: '{{ ddns.user_name }}'
    mode: 0755

- name: setting cron
  become: True
  cron:
    name: ddns
    user: '{{ ddns.user_name }}'
    minute: "*/5"
    job: "python3 /opt/ddns/ddns.py {{ minecraft.domain_name }} {{ minecraft.hostname }}"
    state: present

- name: make logrotate setting
  copy:
    src: ./etc/logrotate.d/ddns
    dest: /etc/logrotate.d/ddns
    owner: root
    group: root
    mode: 0644
