---

- name: Setting common 
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - name: common

- name: Setting Minecraft
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - name: minecraft

- name: Setting firewall
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - name: firewall

- name: Setting ddns
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - name: ddns
